apiVersion: apps/v1
kind: Deployment
metadata:
  name: rriv-api
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject-secret-config: "secret/data/prod-auth-api-creds"
        vault.hashicorp.com/agent-inject-template-config: |
          {{ with secret "secret/data/prod-auth-api-creds" }}
          OPENFGA_STORE_ID="{{ .Data.data.openfga_store_id }}"
          OPENFGA_MODEL_ID="{{ .Data.data.openfga_model_id }}"
          {{ end }}
    spec:
      containers:
        - name: rriv-api
          env:
            - name: KEYCLOAK_URL
              value: https://auth.rriv.org
            - name: KEYCLOAK_REALM
              value: rriv-beta-prod
            - name: OPENFGA_URL
              value: http://rriv-openfga:8080
