name: Deploy to Environment
on:
  workflow_dispatch:
    inputs:
      env:
        description: "Environment to deploy to"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - staging
          - prod
      tag:
        description: "Specify tag to deploy"
        required: true

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    env:
      ENV: ${{ github.event.inputs.env }}
      TAG: ${{ github.event.inputs.tag }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out the github actions repo
        uses: actions/checkout@v5
        with:
          repository: rrivirr/github-actions
          ref: v1.1.0
          token: ${{ secrets.GH_ACTIONS_ACCESS_TOKEN }}
          path: ./.github/actions/rrivirr-github-actions
      - name: Prepare deployment
        uses: ./.github/actions/rrivirr-github-actions/.github/actions/prepare-deployment.yaml@v1.1.0 # make sure you point at the latest version!
        with:
          ENV: ${{ env.ENV }}
          # This line is required to pass the AWS role to the action
          AWS_ROLE_ARN: ${{ secrets[format('{0}_GITHUB_ACTIONS_AWS_ROLE_ARN', env.ENV)] }}

      - name: Install kustomize
        run: curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash

      - name: Update image tag
        run: (cd deployment/overlays/${{env.ENV}} && kustomize edit set image registry.digitalocean.com/rriv/auth-api:${{ env.TAG }})

      - name: apply update
        run: kustomize build deployment/overlays/${{env.ENV}} | kubectl apply --wait -f -
